### ISSUE TITLE
Code Duplication in SNN::doCurrentUpdate()

### ISSUE THREAD

**Issue by SigmaX** [UCI-CARL/CARLsim5#12]
While investigating issue #11, I noticed that `SNN::doCurrentUpdate()` duplicates two near-identical `for` loops (see [here](https://github.com/UCI-CARL/CARLsim5/blob/master/carlsim/kernel/src/snn_manager.cpp#L2420)).

This is unusual, and it's not clear whether it is intentional, or was done for a reason.  Should be investigated to either correct or add a clarifying comment.

**Comment by nmsutton** [comment]
@SigmaX I think that while the loops are very similar the key difference is that doCurrentUpdateD1_GPU(netId) or doCurrentUpdateD2_GPU(netId) are run seperately in them. "D1" is for "updating and generating spikes on connections with a delay of 1ms" and "D2" is for "delays greater than 1". Certainly, the code redundancy in the loops could be improved but I think the loops do two different things. I think perhaps "D2" is purposefully run before "D1". This issue however could stay open if wanted because a non-duplicated code version of the programming could be done to improve the code.

**Comment by SigmaX** [comment]
Thanks @nmsutton.  I [added comments](https://github.com/UCI-CARL/CARLsim6/commit/cf0358a56b1f5efde579e8c062c6bff485be9d28) to the equivalent location in CARLsim6 to clarify.

Closing this, as the main point was to make sure there was not a bug.

I would take a stab at removing the redundancy/doing some local cleanup there (like adding function docs, which are needed throughout the file), but I can't tell if that code is covered by unit tests or not. I don't dare refactor things without a low-level test harness.

**Comment by nmsutton** [comment]
@SigmaX You're welcome and thanks for adding the code comments.
